on:
  pull_request:
    branches:
      - main

jobs:
  test-windows:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: stable
      - name: Unit tests
        run: go test ./...

  CI:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: stable

      - name: Setup Cue
        run: go install cuelang.org/go/cmd/cue@v0.17.0-0.dev.0.20260320151706-d267795de4d3

      - name: Regenerate types from Gemara spec
        run: |
           make generate

      - name: Check for uncommitted changes
        run: |
           if [ -n "$(git status --porcelain)" ]; then
             echo "Error: Generated types are out of sync with the Gemara specification"
             echo "The following files have uncommitted changes:"
             git status --porcelain
             echo ""
             echo "Please run 'make generate' locally and commit the changes."
             exit 1
           else
             echo "Generated types are in sync with the Gemara specification"
           fi

      - name: Vet
        run: |
          go vet ./...

      - name: Unit tests
        run: |
          make testcov

      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 71
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi
